# Generated by Django 4.2.18 on 2025-03-02 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletter', '0003_alter_newslettersubscriber_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='email',
        ),
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_subscription', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
