# Generated by Django 4.2.18 on 2025-02-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crashpad',
            name='dimensions',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
