# Generated by Django 4.2.18 on 2025-02-22 10:46

from django.db import migrations, models
import django.db.models.deletion
import rentals.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_crashpad_dimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashpadGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=rentals.models.crashpad_gallery_upload_path)),
                ('crashpad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='rentals.crashpad')),
            ],
        ),
    ]
