# Generated by Django 4.2.18 on 2025-02-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_crashpadgalleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crashpad',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='crashpad',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
