# Generated by Django 4.2.18 on 2025-02-26 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orderitem_check_in_remove_orderitem_check_out_and_more'),
        ('rentals', '0005_remove_crashpad_price_per_day_crashpad_day_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashpadBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental_days', models.IntegerField(editable=False)),
                ('customer_name', models.CharField(editable=False, max_length=255)),
                ('customer_email', models.EmailField(editable=False, max_length=254)),
                ('customer_phone', models.CharField(editable=False, max_length=20)),
                ('crashpad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.crashpad')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crashpads', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
