# Generated by Django 4.2.18 on 2025-03-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_crashpadbooking_delete_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crashpadbooking',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='crashpadbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
