# Generated by Django 4.2.18 on 2025-02-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_country_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_line2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(auto_created=True, default='FD4997A7E8DA41BEB4D28F95B2BA5266', editable=False, max_length=32, unique=True),
        ),
    ]
