# Generated by Django 4.2.18 on 2025-02-26 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_slug_alter_product_description'),
        ('orders', '0006_orderitem_check_in_orderitem_check_out_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='crashpad',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='rental_days',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='type',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
            preserve_default=False,
        ),
    ]
