# Generated by Django 4.2.18 on 2025-02-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orderitem_check_in_remove_orderitem_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='handling_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('products_only', 'Products Only'), ('rentals_only', 'Rentals Only'), ('mixed', 'Products and Rentals')], max_length=20, null=True),
        ),
    ]
