# Generated by Django 4.2.18 on 2025-02-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_handling_fee_order_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='original_cart',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('PRODUCTS_ONLY', 'Products Only'), ('RENTALS_ONLY', 'Rentals Only'), ('MIXED', 'Products and Rentals')], max_length=20, null=True),
        ),
    ]
