name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
  
    # Use a dedicated action for setting up Chrome and ChromeDriver
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
    
    # Use a dedicated action for setting up ChromeDriver
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Run Tests
      env:
        DATABASE_URL: "sqlite:///test_db.sqlite3"
      run: |
        # Temporary fix for settings.py path issue
        sed -i "s/BASE_DIR \/ \"test_db.sqlite3\"/os.path.join(BASE_DIR, \"test_db.sqlite3\")/g" bouldering_cy/settings.py
        python manage.py test
